[bot]
TOKEN = "XXX"

[userbot]
API_ID = 123
API_HASH = "xxx"
PHONE = "+123"

[chats]
LINKS = ["-1", "-1", "-1", "-1"]

[detect]
PHRASES = ["куплю покрышки", "купить покрышки", "ищу покрышки", 'ишу покрышки', "нужны покрышки", "куплю шины",
				"купить шины", "ищу шины", "нужны шины", "купю резину", "купить резину", 'ищу резину', 'нужна резина',
				"продам покрышки", "продаю покрышки", "продажа покрышек", 'продам шины', "продаю шины", "продажа шин",
				"продам резину", "продажа резины", 'продаю резину', 'ишу шины', 'ишу резину']
